### PR TITLE
#137 move association to flyout

### PR DESCRIPTION
**Pull request by jmecosta**
handles  #137

### CODE REVIEW

**Comment by jmecosta** [comment]
@Bertk, can you try this new version? i think it should now handle your requirement. plus for some reason the translation of msbuild keys was not really correct at least with last version of msbuild runner

**Comment by Bertk** [comment]
Sure I will test it during the weekend. Please point me to a installation package. I have some problems to build it.

**Comment by jmecosta** [comment]
I will, in still need to fix something in the PR that I notice. I will put the link to it when it's ready

**Comment by jmecosta** [comment]
@Bertk if you follow the appveyour build in this pr, you can get to the artifacts and download the one you need. 


this is how it looks now:

image

**Comment by jmecosta** [comment]
@Bertk you can use the last version in master: https://ci.appveyor.com/project/TeklaCorp/vssonarqubeextension

the easiest to test this, is to remane to vsix to zip and extract the dlls and copy all dlls in root on top of your existing instalation so you can still use the installed plugins

**Pull request merged**
